---

apiVersion: v1
kind: Namespace
metadata:
  name: guestbook-go

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-go
  namespace: argocd
spec:
  destination:
    namespace: guestbook-go
    server: 'https://kubernetes.default.svc'
  source:
    path: guestbook-go
    repoURL: 'https://github.com/kubernetes/examples.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

