---

apiVersion: v1
kind: Namespace
metadata:
  name: sock-shop

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sock-shop
    server: 'https://kubernetes.default.svc'
  source:
    path: 'slack-sock-shop'
    repoURL: 'https://github.com/MrFreezeex/argocd-example-apps.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
